stages:
  prepare:
    cmd: python -m src.data.preprocess_dataset
    deps:
    - src/data/raw/
    - src/data/preprocess_dataset.py
    params:
    - prepare
    outs:
    - src/data/processed/
  train:
    cmd: python -m src.models.train_model
    deps:
    - src/data/processed/
    - src/models/train_model.py
    params:
    - train
    outs:
    - models/

