stages:
  prepare:
    cmd: python -m src.data.preprocess_dataset
    deps:
    - data/raw/
    - src/data/preprocess_dataset.py
    params:
    - dataset
    outs:
    - data/processed/
    - gx/uncommited/data_docs/
  train:
    cmd: python -m src.models.train_model
    deps:
    - data/processed/
    - src/models/train_model.py
    params:
    - model
    outs:
    - models/final_model/
  test: 
    cmd: python -m src.models.test_model
    deps:
    - data/processed/
    - models/final_model/
    - src/models/test_model.py
    params:
    - model