dataset:
  audio_length: 1 # audio length in sec
  total_labels: 36 # for one hot encoding
  feature_extractor: "facebook/hubert-base-ls960"
model:
  algorithm_name: "Hubert_Classifier"
  random_state: 33 #seed for reproducibility
  num_classes: 36 # total possible classifications

  batch_size: 256 # training and valid batch size
  lr: 0.00001 # learning rate
  momentum: 0.9 # SGD momentum, for SGD only
  optimizer: 'adam' # optimization method: sgd | adam
  adapter_hidden_size: 128 # model hyperparameter

  epochs: 100  # maximum number of epochs to train
  patience: 5 # how many epochs of no loss improvement should we wait before stop training
  log_interval: 15 # how many batches to wait before logging training status
  